### ISSUE TITLE
How to comment a line in the feature file

### ISSUE THREAD

**Issue by Syslog2905** [Marketionist/protractor-cucumber-steps#15]
Hi, good work! But how can I comment a line in the feature file? I tried everything that comes into my mind like #, //, /* - nothing works.

**Comment by Marketionist** [comment]
Hello @Syslog2905 and thanks! You can add comments in `.feature` files using `#` for single line comments. Multiline (or block) comments are not supported in Gherkin out of the box (see https://github.com/cucumber/gherkin/issues/203), so you have to prefix all lines with `#` like this:
```
# Test single line comment 1
# Test single line comment 2
Scenario: Commit to open source should be joyful
  When I commit
  Then I get a star
  # And a commented out step
```

I plan to update [README.md](https://github.com/Marketionist/protractor-cucumber-steps/blob/master/README.md) with this instructions soon
