### ISSUE TITLE
Please update cucumber.js

### ISSUE THREAD

**Issue by Syslog2905** [Marketionist/protractor-cucumber-steps#16]
Hi, there is "cucumber": "^2.3.0" for java script already which I started to use recently. It has much better syntax so you may consider updating it.
Once updated I can contribute to update step definitions with the new syntax.

**Comment by Marketionist** [comment]
Hello @Syslog2905, nice catch, I'll bump up cucumber to "^2.3.0". Your contributions are always welcome!

**Comment by Marketionist** [comment]
I bumped up cucumber to "^2.3.0", so you can add updated step definitions to this PR https://github.com/Marketionist/protractor-cucumber-steps/pull/18. Thanks for your contributions @Syslog2905!
