### ISSUE TITLE
webdriver-manager update

### ISSUE THREAD

**Issue by inwaar** [Marketionist/protractor-cucumber-steps#59]
For some reason it requires to have `webdriver-manager` installed globally, whereas it's in `node_modules/protractor/bin/webdriver-manager`.

```
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! protractor-cucumber-steps@1.3.1 postinstall: `webdriver-manager update`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the protractor-cucumber-steps@1.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by inwaar** [comment]
What is more interesting if I don't want to use Selenium at all (but some like https://gitlab.com/DMore/behat-chrome-extension) this postinstall will download it anyway.

**Comment by Marketionist** [comment]
@inwaar please try the updated version of `protractor-cucumber-steps` (1.3.2) - is it ok now?
