### ISSUE TITLE
How to use dynamic xpaths in this

### ISSUE THREAD

**Issue by Ducistech** [Marketionist/protractor-cucumber-steps#69]
Hello

Tried this framework but stuck when i need to use dynamic xath

**Comment by Marketionist** [comment]
Hello @Ducistech,

You can add XPath selectors to your page objects like here - https://github.com/Marketionist/protractor-cucumber-steps/blob/master/tests/page_objects/test.page.js#L8 and then use them in your spec files. Do hesitate to reach out - I'll be happy to help.
