### ISSUE TITLE
Package breaks if on windows (Powershell)

### ISSUE THREAD

**Issue by shyamshi** [Marketionist/protractor-cucumber-steps#75]
Hi, I happen to be using NPM over PowerShell, and the **postscript** install fails due to the '&&'.

Can you please fix this? 

Cheers

**Comment by Marketionist** [comment]
Hello @shyamshi, thanks for filing the issue. Will be fixed soon in v1.3.7

**Comment by Marketionist** [comment]
Fix was merged and published - `protractor-cucumber-steps@1.3.7` @shyamshi does it work ok for you?

**Comment by PauloGoncalvesBH** [comment]
This solution doesn't work on windows, I opened the issue #78

**Comment by PauloGoncalvesBH** [comment]
Added a review on Pull Request #76
