### ISSUE TITLE
Getting Stale Element Error while running the script over Remote Serever

### ISSUE THREAD

**Issue by Ducistech** [Marketionist/protractor-cucumber-steps#83]
I am Running the Protractor script over a remote server, but i am getting stale Element error even the element is present on the screen.

also sometime it doesn't wait for page to load and exit with error no Element found using locator.

can you please help here

**Comment by Marketionist** [comment]
Hello @Ducistech, thanks for the question. You can use `protractor.ExpectedConditions` to wait for the element to appear on the page - see some examples:
- http://www.protractortest.org/#/api?view=ProtractorExpectedConditions,
- https://medium.com/@sdet.ro/how-to-use-smart-waits-with-protractor-how-to-use-expected-conditions-with-protractor-10c545c670be
